### PR TITLE
Fix CWManage cloud API URL, device retrieval, and warranty end date format

### PR DESCRIPTION
**Pull request by mdewart-springpoint**
Pulls the latest API info from /login/companyinfo/connectwise (each new release updates the API URL), and corrects the $CWMAPIURL variable.

Example output of Invoke-RestMethod -Headers $header -Method GET -Uri "$CWMAPIURL/login/companyinfo/connectwise"
where $CWMAPIURL = 'https://na.myconnectwise.net'

CompanyName : ConnectWise
Codebase : v2020_4/
VersionCode : v2020.4
VersionNumber : v4.6.77997
CompanyID : CW
IsCloud : True
SiteUrl : api-na.myconnectwise.net
AllowedOrigins : {*.connectwisedev.com, *.myconnectwise.net, *.connectwise.net, cw.connectwise.net...}

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
Silly question, how does this operate for non-cloud customers? :) would happily merge, just don't know enough of CWM.

**Comment by mdewart-springpoint** [comment]
According to their developer page:

Cloud vs Premise
A cloud environment will return a codebase that has the ConnectWise Manage version.  On-Premise does not use URL redirection and will return v4_6_release/.  If your returned codebase contains anything other than v4_6_release/, you will need to ensure your request is prefixed by API-

Perhaps a check for cloud would be in order too, but I don't have an on-prem to test against.

--
Matthew Dewart

**Comment by mdewart-springpoint** [comment]
If you want to simply modify it to

   If (!($CWMAPIURL -match 'api')) {
        $companyinfo = Invoke-RestMethod -Headers $header -Method GET -Uri "$CWMAPIURL/login/companyinfo/connectwise"
        If ($companyinfo.IsCloud) {
            $CWMAPIURL = https://$($companyinfo.siteurl)/$($companyinfo.Codebase)apis/3.0
        }
    }

That should prevent it from rewriting on-prem URLs.

--
Matthew Dewart

From: Matt Dewart
Sent: Friday, April 2, 2021 3:23 PM
To: KelvinTegelaar/PowerShellWarrantyReports ***@***.***>; KelvinTegelaar/PowerShellWarrantyReports ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [KelvinTegelaar/PowerShellWarrantyReports] Corrects the API URL when provided with only the regional URL (#32)

According to their developer page:

Cloud vs Premise
A cloud environment will return a codebase that has the ConnectWise Manage version.  On-Premise does not use URL redirection and will return v4_6_release/.  If your returned codebase contains anything other than v4_6_release/, you will need to ensure your request is prefixed by API-

Perhaps a check for cloud would be in order too, but I don't have an on-prem to test against.

--
Matthew Dewart

**Comment by mdewart-springpoint** [comment]
/login/companyinfo/connectwise should be /login/companyinfo/$cwcompanyid too... I can resubmit if you like.

--
Matthew Dewart

From: Matt Dewart
Sent: Friday, April 2, 2021 3:25 PM
To: 'KelvinTegelaar/PowerShellWarrantyReports' ***@***.***>; 'KelvinTegelaar/PowerShellWarrantyReports' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [KelvinTegelaar/PowerShellWarrantyReports] Corrects the API URL when provided with only the regional URL (#32)

If you want to simply modify it to

   If (!($CWMAPIURL -match 'api')) {
        $companyinfo = Invoke-RestMethod -Headers $header -Method GET -Uri "$CWMAPIURL/login/companyinfo/connectwise"
        If ($companyinfo.IsCloud) {
            $CWMAPIURL = https://$($companyinfo.siteurl)/$($companyinfo.Codebase)apis/3.0
        }
    }

That should prevent it from rewriting on-prem URLs.

--
Matthew Dewart

From: Matt Dewart
Sent: Friday, April 2, 2021 3:23 PM
To: KelvinTegelaar/PowerShellWarrantyReports ***@***.******@***.***>>; KelvinTegelaar/PowerShellWarrantyReports ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [KelvinTegelaar/PowerShellWarrantyReports] Corrects the API URL when provided with only the regional URL (#32)

According to their developer page:

Cloud vs Premise
A cloud environment will return a codebase that has the ConnectWise Manage version.  On-Premise does not use URL redirection and will return v4_6_release/.  If your returned codebase contains anything other than v4_6_release/, you will need to ensure your request is prefixed by API-

Perhaps a check for cloud would be in order too, but I don't have an on-prem to test against.

--
Matthew Dewart

**Pull request merged**
